#:kivy 2.0.0
#:import xcamera kivy_garden.xcamera.xcamera
#:import CaptureScreen libs.capturescreen

<CaptureScreen>:
    name: 'capture'
    md_bg_color: 0, 0, 0, 1
    XCamera:
        id: camera
        on_picture_taken: root.picture_taken(*args)
        canvas.before:
            PushMatrix
            Rotate:
                angle: -90
                origin: self.center
        canvas.after:
            PopMatrix