#:kivy 2.0.0

<GalleryScreen>:
    name: 'gallery'
    md_bg_color: 0, 0, 0, .9
    ScrollView:
        MDGridLayout:
            id: gallery_content
            cols: 3
            adaptive_height: True
            padding: dp(4), dp(4)
            spacing: dp(4)
    MDFloatingActionButtonSpeedDial:
        id: dial
        data: root.data
        icon: "plus"
        callback: root.custom_transition
 