name: Build
on: [push, pull_request]

jobs:
  # Build job. Builds app for Android with Buildozer
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2 
        
      - name: Set version number
        run: |
          $version = '0.0.${{ github.run_number }}'
          echo $version
          echo "VERSION_NUMBER=$version" 

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1.1.3
        id: buildozer
        with:
          workdir: .
          buildozer_version: stable
        env:
          APP_VERSION: ${{ env.VERSION_NUMBER }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: ${{ steps.buildozer.outputs.filename }}
